# Generated by Django 6.0.6 on 2026-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_devtool_alter_idea_devtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtool',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='개발 툴 설명'),
        ),
        migrations.AddField(
            model_name='devtool',
            name='kind',
            field=models.CharField(default='Frontend/Backend', max_length=100, verbose_name='종류'),
        ),
    ]
