# Generated by Django 6.0.7 on 2026-07-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirogram', '0002_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='followings',
        ),
    ]
