# Generated by Django 6.0.6 on 2026-07-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='actor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviereview',
            name='director',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviereview',
            name='running_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
