# Generated by Django 6.0.6 on 2026-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_moviereview_actor_moviereview_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('comedy', '코메디'), ('drama', '드라마'), ('romance', '로맨스'), ('thriller', '스릴러'), ('horror', '공포'), ('sf', 'SF')], max_length=50),
        ),
    ]
