# Generated by Django 6.0.6 on 2026-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_moviereview_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('sf', 'SF')], max_length=50),
        ),
    ]
